### ISSUE TITLE
Implement map API

### ISSUE THREAD

**Issue by breezjirasak** [ISP-Hello-Buddy/Hello-Buddy#52]

**Comment by breezjirasak** [comment]
Did you put all library into the requirements.txt?. I can not run the server.

**Comment by reviseUC73** [comment]
Sorry , From checked I found my requirements.txt  it has wrong program for install.
( `base64 --> change to  --> pybase64` )
Now I changed my requirements.txt so If you can not run program you can try `brew install postgis` .

**Comment by breezjirasak** [comment]
Still error.
