### ISSUE TITLE
Cannot send for contact

### ISSUE THREAD

**Issue by natekrth** [ISP-Hello-Buddy/Hello-Buddy#72]
![Screen Shot 2565-11-23 at 11 26 08](https://user-images.githubusercontent.com/77069581/203469129-73cac798-031e-4ce0-8989-e3422629ada9.png)

**Comment by breezjirasak** [comment]
We do not to use this feature but if you want to contact us you can send us an email.

<img width="288" alt="Screenshot 2565-11-28 at 11 45 36" src="https://user-images.githubusercontent.com/92836354/204195925-080e8855-60ba-45bc-aa00-b5b1f4c168e9.png">
