### ISSUE TITLE
Mannual signup create a Server Error(500) resp code

### ISSUE THREAD

**Issue by Tezigudo** [ISP-Hello-Buddy/Hello-Buddy#78]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80502090/203496766-5eaf4a6b-4b18-4f15-bf9a-d2e912461b0c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80502090/203496824-5f1f3eb3-30de-4999-9851-01ac791ee7c0.png">

**Comment by breezjirasak** [comment]
Already fix let's try.
