### ISSUE TITLE
Activity create more than one after spamming submit button

### ISSUE THREAD

**Issue by Tezigudo** [ISP-Hello-Buddy/Hello-Buddy#80]
button below here
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80502090/203497598-b9c7dbce-a0f9-431c-b35e-e38927e8d8cb.png">

![image](https://user-images.githubusercontent.com/80502090/203497684-1659e5e0-8e2a-4244-bede-caac045224d1.png)

**Comment by breezjirasak** [comment]
Already fix
