### ISSUE TITLE
If the app logo doesn't lead the user anywhere then it shouldn't be clickable

### ISSUE THREAD

**Issue by Hamiz5401** [ISP-Hello-Buddy/Hello-Buddy#81]
![image](https://user-images.githubusercontent.com/92782075/203697557-4c1a74b3-2f49-4c0f-ac44-21e6b8f584fa.png)
![image](https://user-images.githubusercontent.com/92782075/203697578-77f28b7c-0433-4657-b385-98755d65df41.png)

**Comment by breezjirasak** [comment]
already fix. thank you.
