### ISSUE TITLE
After changing setting in the profile page the message popup in the home page but it still redirect at the profile page.

### ISSUE THREAD

**Issue by SeventwoZ** [ISP-Hello-Buddy/Hello-Buddy#82]
![image](https://user-images.githubusercontent.com/91252217/203698773-f69eb7c8-3676-4a6b-9ff2-97289e64cc35.png)
![image](https://user-images.githubusercontent.com/91252217/203698828-71e2967b-20b5-4130-8f3e-7a34a4af4d4d.png)

**Comment by breezjirasak** [comment]
Already fixed let's try.
