### ISSUE TITLE
Can not delete my own event.

### ISSUE THREAD

**Issue by Savetang19** [ISP-Hello-Buddy/Hello-Buddy#83]
You said in your project proposal that "users who create an event can delete their own event," but I can not delete it. (There is no delete button.)
<img width="1440" alt="Screen Shot 2565-11-24 at 22 29 37" src="https://user-images.githubusercontent.com/89629829/203821487-75c5ce43-3fa1-47e6-a967-a36dc4adf4ed.png">
<img width="1440" alt="Screen Shot 2565-11-24 at 22 29 24" src="https://user-images.githubusercontent.com/89629829/203821518-23a528f9-0496-4bde-abe9-c0d0983d54d5.png">

**Comment by breezjirasak** [comment]
Already fixed let's try.
